---
- hosts: webservers
  become: yes
  tasks:
    - name: Install java8
      yum:
        name: java-1.8.0-openjdk
        state: present
    - name: download tomcat8
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.78/bin/apache-tomcat-8.5.78.tar.gz
        dest: /opt/
    - name: check /opt/tomcat folder is present
      stat:
        path: /opt/tomcat
      register: st
    - name: extract the file
      unarchive:
        src: /opt/apache-tomcat-8.5.78.tar.gz
        dest: /opt/
        remote_src: True
      when: not st.stat.exists
    - name: Change file ownership, group and permissions
      file:
        path: /opt/tomcat
        owner: ec2-user
        mode: '0777'

    - name: start and enable tomcat server
      shell: ./startup.sh
      args:
        chdir: /opt/tomcat/bin
    - name: deploy sample app
      copy:
        src: target/maven-archetype-webapp.war
        dest: /opt/tomcat/webapps/
        owner: ec2-user
        group: ec2-user

